apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-standard
provisioner: disk.csi.azure.com
parameters:
  skuname: Standard_LRS
  kind: Managed
  cachingmode: ReadWrite
  fsType: {{ .Values.sc.fsType }}
reclaimPolicy: Retain
